spring.application.name=ms-rabbit-admin
server.port=${SERVER_PORT:8093}

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:smartlogix}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:smartlogix123}

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
