server.port=8080
spring.application.name=bff-smartlogix

# URLs de los microservicios downstream
inventario.url=http://localhost:8081
pedidos.url=http://localhost:8082
envios.url=http://localhost:8083
